// AUTO-GENERATED by scripts/sync-calendar-data.mjs — DO NOT EDIT BY HAND.
//
// Offline seed used only on a first launch with no network. The calendar JSON's single
// source of truth is public/data/ in the orthodox-korea-calendar repo — edit it there,
// then run `npm run sync:calendar-data`. `npm run check:calendar-data` fails on drift.

type BundledYear = { en: unknown; kr: unknown };

export const BUNDLED_CALENDAR_YEARS: Record<number, () => BundledYear> = {
  2026: () => ({
    en: require('../../../assets/webapp-source/data/2026_en.json'),
    kr: require('../../../assets/webapp-source/data/2026_kr.json'),
  }),
};
